<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css"/>
        <script src="bootstrap/js/jquery.min.js" type="text/javascript"></script>
        <script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <script src="js/app.js" type="text/javascript"></script>
        <style>

        </style>
    </head>
    <body>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">LISTADO DE EMPLEADOS</h3>
            </div>
            <form id="frmEmployee" role="form" class="form-horizontal">
                <div class="panel-body ">

                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="email" class="col-md-3 control-label">Fecha:</label>
                                    <div class="col-md-9">
                                        <input required="" name="email" id="email" type="email" class="form-control input-sm" placeholder="correo@email.com">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            <div class="panel-footer form-actions fluid">
                <button title="Buscar" id="btnBuscar" type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Buscar</button>      
            </div>
                </form>
            <div class="panel-body">
                <table id="tbEmployees" class="table table-bordered table-hover table-full-width-dataTable table-condensed">
                    <thead>
                        <tr>
                            <th>VER</th>
                            <th>NAME</th>
                            <th>EMAIL</th>
                            <th>POSITION</th>
                            <th>SALARY</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
        </div>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Detalle Empleado</h4>
                    </div>
                    <div class="modal-body">
                        <div class="panel-body  form-horizontal">
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label  class="col-md-3 control-label">Name:</label>
                                            <div class="col-md-9">
                                                <label id="lblName" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label   class="col-md-3 control-label">Email:</label>
                                            <div class="col-md-9">
                                                <label id="lblEmail" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label   class="col-md-3 control-label">Phone:</label>
                                            <div class="col-md-9">
                                                <label id="lblPhone" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label  class="col-md-3 control-label">Address:</label>
                                            <div class="col-md-9">
                                                <label id="lblAddress" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="fechaInicial" class="col-md-3 control-label">Position:</label>
                                            <div class="col-md-9">
                                                <label id="lblPosition" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="fechaInicial" class="col-md-3 control-label">Salary:</label>
                                            <div class="col-md-9">
                                                <label id="lblSalary" class="control-label">Name:</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-body">
                                <table id="tbSkill" class="table table-bordered table-hover table-full-width-dataTable table-condensed">
                                    <thead>
                                        <tr>
                                            <th>SKILL</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
